stages:
  completion:
    cmd: PYTHONPATH=. shtab foo.parser -s bash > foo_completion.sh
    deps:
    - foo.py
    outs:
    - foo_completion.sh
  out:
    cmd: python foo.py -o out.txt
    deps:
    - foo.py
    outs:
    - out.txt
