stages:
  completion:
    cmd: shtab foo.parser -s bash > foo_completion.sh
    deps:
    - foo.py
    outs:
    - foo_completion.sh
  out:
    cmd: python foo.py -o out.txt
    deps:
    - pyextract.py
    - foo.py:
        cmd: python pyextract -f main,foo
    outs:
    - out.txt
